const r = require('express').Router();
const h = require('../utils/asyncHandler');
const auth = require('../middleware/auth');
const roles = require('../middleware/roles');
const c = require('../controllers/reservas.controller');
r.use(auth);
r.get('/', h(c.listar));
r.post('/', h(c.crear));
r.post('/:id/confirmar', roles('ADMIN'), h(c.confirmar));
r.post('/:id/cancelar', h(c.cancelar));
r.delete('/:id', h(c.cancelar));
module.exports = r;
